#  Processing Laboratory - Mercury_Inorganic_Blood(IHG) file

In [1]:
import numpy as np
import pandas as pd
import glob 
import os
import sys

In [2]:
os.getcwd()

'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Code'

In [3]:
path = 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab'
allFiles = glob.glob(os.path.join(path,"*.XPT"))
print(allFiles)

['C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\ALB_CR_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\APOB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\BIOPRO_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\CARB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\CBC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\CHLMDA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\COTNAL_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\CRP_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\DEET_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\EPH_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\FASTQX_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\FERTIN_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\FOLATE_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\FOLFMS_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\GHB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\GLU_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HDL_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HEPA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HEPBD_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HEPB_S_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HEPC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HIV_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HPVSER_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HPVSWR_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HSV_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\IHG_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\OGTT_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\OPD_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PAH_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PBCD_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PERNT_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PFC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PHTHTE_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PHYTO_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PP_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PSA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\SSEBV_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\SSHCV_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\SSUSG_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\TCHOL_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\TFR_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\THYROD_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\TRIGLY_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UAM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UAS_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UCPREG_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UHG_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UHM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UIO_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UPHOPM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UPP_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VID_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VIT_B6_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VOCMWB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VOCWB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VOC_E.XPT']

In [4]:
IHG = pd.read_sas('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\IHG_E.XPT', index='SEQN')
IHG.shape

(9307, 3)

In [5]:
A = set(IHG.columns)
print(sorted(A))

['LBDIHGLC', 'LBDIHGSI', 'LBXIHG']

In [7]:
IHG.describe().T

           count      mean       std           min   25%   50%   75%    max
LBXIHG    8162.0  0.318204  0.233392  2.500000e-01  0.25  0.25  0.25  14.00
LBDIHGSI  8162.0  1.590051  1.164026  1.250000e+00  1.25  1.25  1.25  69.86
LBDIHGLC  8162.0  0.772115  0.419494  5.397605e-79  1.00  1.00  1.00   1.00

In [9]:
IHG.reset_index()

         SEQN  LBXIHG  LBDIHGSI      LBDIHGLC
0     41475.0    0.25      1.25  1.000000e+00
1     41476.0    0.25      1.25  1.000000e+00
2     41477.0    0.25      1.25  1.000000e+00
3     41478.0     NaN       NaN           NaN
4     41479.0    0.25      1.25  1.000000e+00
5     41480.0     NaN       NaN           NaN
6     41481.0     NaN       NaN           NaN
7     41482.0    0.25      1.25  1.000000e+00
8     41483.0    0.25      1.25  1.000000e+00
9     41485.0    0.25      1.25  1.000000e+00
10    41486.0    0.25      1.25  1.000000e+00
11    41487.0    0.25      1.25  1.000000e+00
12    41488.0    0.25      1.25  1.000000e+00
13    41489.0    0.25      1.25  1.000000e+00
14    41490.0    0.45      2.25  5.397605e-79
15    41491.0    0.60      2.99  5.397605e-79
16    41492.0    0.25      1.25  1.000000e+00
17    41493.0    0.25      1.25  1.000000e+00
18    41494.0    0.25      1.25  1.000000e+00
19    41495.0    0.25      1.25  1.000000e+00
20    41496.0    0.61      3.04  5.397605e-79
21    41497.0    0.25      1.25  1.000000e+00
22    41498.0    0.25      1.25  1.000000e+00
23    41499.0    0.42      2.10  5.397605e-79
24    41500.0    0.25      1.25  1.000000e+00
25    41501.0    0.25      1.25  1.000000e+00
26    41502.0    0.25      1.25  1.000000e+00
27    41503.0    0.25      1.25  1.000000e+00
28    41504.0    0.25      1.25  1.000000e+00
29    41505.0    0.52      2.59  5.397605e-79
...       ...     ...       ...           ...
9277  51590.0    0.25      1.25  1.000000e+00
9278  51591.0     NaN       NaN           NaN
9279  51592.0    0.25      1.25  1.000000e+00
9280  51593.0    0.48      2.40  5.397605e-79
9281  51594.0    0.25      1.25  1.000000e+00
9282  51596.0    0.25      1.25  1.000000e+00
9283  51597.0    0.25      1.25  1.000000e+00
9284  51599.0     NaN       NaN           NaN
9285  51600.0     NaN       NaN           NaN
9286  51601.0    0.25      1.25  1.000000e+00
9287  51603.0    0.25      1.25  1.000000e+00
9288  51604.0    0.25      1.25  1.000000e+00
9289  51606.0    0.25      1.25  1.000000e+00
9290  51607.0     NaN       NaN           NaN
9291  51608.0    0.25      1.25  1.000000e+00
9292  51609.0    0.25      1.25  1.000000e+00
9293  51610.0    0.25      1.25  1.000000e+00
9294  51611.0    0.25      1.25  1.000000e+00
9295  51612.0    0.25      1.25  1.000000e+00
9296  51613.0    0.25      1.25  1.000000e+00
9297  51614.0    0.25      1.25  1.000000e+00
9298  51615.0     NaN       NaN           NaN
9299  51616.0    0.37      1.85  5.397605e-79
9300  51617.0    0.58      2.89  5.397605e-79
9301  51618.0    0.25      1.25  1.000000e+00
9302  51619.0    0.25      1.25  1.000000e+00
9303  51620.0    0.36      1.80  5.397605e-79
9304  51621.0    0.25      1.25  1.000000e+00
9305  51622.0    0.25      1.25  1.000000e+00
9306  51623.0    0.70      3.49  5.397605e-79

[9307 rows x 4 columns]

In [8]:
IHG.to_csv('IHG_Lab_filter.csv')

# Processing Column of IHG

In [6]:
# Inorganic mercury ug/l
IHG_reading1 = IHG['LBXIHG']
print('IHG_reading1 shape = ', IHG_reading1.shape)
print(IHG_reading1.head())
print(IHG_reading1.describe())

IHG_reading1 shape =  (9307,)
SEQN
41475.0    0.25
41476.0    0.25
41477.0    0.25
41478.0     NaN
41479.0    0.25
Name: LBXIHG, dtype: float64
count    8162.000000
mean        0.318204
std         0.233392
min         0.250000
25%         0.250000
50%         0.250000
75%         0.250000
max        14.000000
Name: LBXIHG, dtype: float64

In [7]:
# Inorganic mercury comment yes or no
IHG_reading2 = IHG['LBDIHGLC']
print('IHG_reading2 shape = ', IHG_reading2.shape)
print(IHG_reading2.head())
print(IHG_reading2.describe())

IHG_reading2 shape =  (9307,)
SEQN
41475.0    1.0
41476.0    1.0
41477.0    1.0
41478.0    NaN
41479.0    1.0
Name: LBDIHGLC, dtype: float64
count    8.162000e+03
mean     7.721147e-01
std      4.194939e-01
min      5.397605e-79
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
Name: LBDIHGLC, dtype: float64

In [9]:
print('IHG_reading1 missing values =  ', IHG_reading1.isnull().sum(), 'from ', IHG_reading1.shape[0], 'observations')
print('IHG_reading2 missing values =  ', IHG_reading2.isnull().sum(), 'from ', IHG_reading2.shape[0], 'observations')

IHG_reading1 missing values =   1145 from  9307 observations
IHG_reading2 missing values =   1145 from  9307 observations

In [10]:
IHG.describe()

            LBXIHG     LBDIHGSI      LBDIHGLC
count  8162.000000  8162.000000  8.162000e+03
mean      0.318204     1.590051  7.721147e-01
std       0.233392     1.164026  4.194939e-01
min       0.250000     1.250000  5.397605e-79
25%       0.250000     1.250000  1.000000e+00
50%       0.250000     1.250000  1.000000e+00
75%       0.250000     1.250000  1.000000e+00
max      14.000000    69.860000  1.000000e+00