#  Processing Questionnaire - CBQPFA (Consumer behavior) file

In [1]:
import numpy as np
import pandas as pd
import glob 
import os
import sys

In [2]:
os.getcwd()

'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Code'

In [ ]:
# Select working directory
# %cd C:\Users\Ganga\Desktop\Research\CDCDiab_2.0\Data\07-08\Examination
#%cd /Users/elgayaro/Main/Research/Healthcare/CDC-NHANES/Data/07-08/Examination

In [ ]:
#os.getcwd()

In [ ]:
#allFiles = glob.glob(os.path.join('.',"*.XPT"))
#print(allFiles)

In [ ]:
# Set desired file name
# fname = '.\\BMX_E.XPT'  # Ganga
#fname = './BMX_E.XPT'   # Omar
#BMX = pd.read_sas(fname, index='SEQN')
#BMX.shape

In [3]:
path = 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest'
allFiles = glob.glob(os.path.join(path,"*.XPT"))
print(allFiles)

['C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ACQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ALQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\AQQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\AUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\BHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\BPQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQPFA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQPFC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CDQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DBQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DPQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ECQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\FSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HOQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\IMQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\INQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\KIQ_P_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\KIQ_U_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\MCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PAQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PFQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PUQMEC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RDQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RXQ_RX_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SLQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQFAM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQRTU_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SXQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\VIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\WHQMEC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\WHQ_E.XPT']

In [4]:
CBQPFA = pd.read_sas('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQPFA_E.XPT', index='SEQN')
CBQPFA.shape

(6022, 57)

In [5]:
CBQPFC = pd.read_sas('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQPFC_E.XPT', index='SEQN')
CBQPFC.shape

(2869, 56)

In [6]:
CBQPFA = CBQPFA.filter(['CBQ505','CBQ520','CBQ525','CBQ530','CBQ535','CBQ550','CBQ565','CBQ570','CBQ575','CBQ665'])

In [7]:
CBQPFC = CBQPFC.filter(['CBQ505','CBQ520','CBQ525','CBQ530','CBQ535','CBQ550','CBQ565','CBQ570','CBQ575','CBQ665'])

In [8]:
CBQPFA.describe().T

         count      mean       std  min  25%  50%  75%  max
CBQ505  4819.0  1.137995  0.369901  1.0  1.0  1.0  1.0  9.0
CBQ520  4166.0  1.855257  0.445255  1.0  2.0  2.0  2.0  9.0
CBQ525  4166.0  1.196591  0.474561  1.0  1.0  1.0  1.0  9.0
CBQ530  4164.0  1.530740  0.592017  1.0  1.0  2.0  2.0  9.0
CBQ535  4164.0  1.871037  0.689607  1.0  2.0  2.0  2.0  9.0
CBQ550  4815.0  1.173001  0.407881  1.0  1.0  1.0  1.0  9.0
CBQ565  3998.0  1.750125  0.528255  1.0  1.0  2.0  2.0  9.0
CBQ570  3998.0  1.341921  0.604295  1.0  1.0  1.0  2.0  9.0
CBQ575  3998.0  1.209855  0.528150  1.0  1.0  1.0  1.0  9.0
CBQ665  4787.0  1.420723  0.739414  1.0  1.0  1.0  2.0  9.0

In [9]:
CBQPFC.describe().T

         count      mean       std  min  25%  50%  75%  max
CBQ505  2249.0  1.081369  0.273463  1.0  1.0  1.0  1.0  2.0
CBQ520  2065.0  1.900242  0.299749  1.0  2.0  2.0  2.0  2.0
CBQ525  2065.0  1.238741  0.426417  1.0  1.0  1.0  1.0  2.0
CBQ530  2065.0  1.531719  0.499114  1.0  1.0  2.0  2.0  2.0
CBQ535  2065.0  1.868281  0.859334  1.0  2.0  2.0  2.0  9.0
CBQ550  2248.0  1.212189  0.408949  1.0  1.0  1.0  1.0  2.0
CBQ565  1771.0  1.756635  0.528354  1.0  1.0  2.0  2.0  9.0
CBQ570  1771.0  1.387352  0.628996  1.0  1.0  1.0  2.0  9.0
CBQ575  1770.0  1.208475  0.406333  1.0  1.0  1.0  1.0  2.0
CBQ665  2244.0  1.308378  0.538571  1.0  1.0  1.0  2.0  9.0

In [10]:
CBQPFA.describe().T.to_csv('CBQPFA_Select.csv')

In [11]:
CBQPFC.describe().T.to_csv('CBQPFC_Select.csv')

In [10]:
CBQPFA.reset_index()

,SEQN,CBQ505,CBQ520,CBQ525,CBQ530,CBQ535,CBQ550,CBQ565,CBQ570,CBQ575,CBQ665
0,41475.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,2.0
1,41477.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0
2,41479.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0
3,41481.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
4,41482.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0
5,41483.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0
6,41485.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
7,41486.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0
8,41487.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0
9,41489.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0
10,41490.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0
11,41492.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,1.0,1.0,1.0
12,41493.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
13,41494.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,41495.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0
15,41496.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0
16,41498.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,41499.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0
18,41501.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,1.0,1.0,1.0
19,41502.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0
20,41503.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,41504.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0
22,41506.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,41509.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
24,41510.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0
25,41511.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,41512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,41514.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,41516.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
29,41518.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
5992,51579.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5993,51580.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,3.0
5994,51581.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5995,51583.0,1.0,2.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,1.0
5996,51584.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0
5997,51585.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5998,51587.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0
5999,51589.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
6000,51590.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0
6001,51591.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6002,51592.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6003,51593.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0
6004,51594.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0
6005,51596.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0
6006,51603.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6007,51604.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
6008,51606.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
6009,51608.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0
6010,51609.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0
6011,51610.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0
6012,51611.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
6013,51614.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,3.0
6014,51616.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0
6015,51617.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0
6016,51618.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
6017,51619.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0
6018,51620.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0
6019,51621.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
6020,51622.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6021,51623.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN

In [11]:
CBQPFA.to_csv('CBQPFA_Ques_filter.csv')

In [12]:
CBQPFC.reset_index()

,SEQN,CBQ505,CBQ520,CBQ525,CBQ530,CBQ535,CBQ550,CBQ565,CBQ570,CBQ575,CBQ665
0,41476.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0
1,41478.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,41480.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0
3,41488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,41491.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
5,41497.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,41500.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,1.0
7,41505.0,1.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,1.0
8,41507.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
9,41508.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,41515.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,41520.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,9.0,1.0,1.0
12,41521.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0
13,41532.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0
14,41533.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
15,41551.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,41553.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,41554.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0
18,41559.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0
19,41560.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0
20,41561.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
21,41564.0,1.0,1.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0
22,41566.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
23,41568.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0
24,41571.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0
25,41582.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0
26,41588.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0
27,41591.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0
28,41593.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0
29,41596.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2839,51523.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0
2840,51526.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0
2841,51528.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0
2842,51529.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,1.0
2843,51531.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
2844,51534.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0
2845,51536.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
2846,51538.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0
2847,51540.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0
2848,51542.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0
2849,51548.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2850,51553.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,51559.0,1.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0
2852,51561.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0
2853,51563.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2854,51565.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0
2855,51567.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0
2856,51571.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0
2857,51573.0,1.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0
2858,51574.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2859,51577.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0
2860,51586.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861,51588.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2862,51597.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
2863,51599.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2864,51600.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0
2865,51601.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0
2866,51607.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0,1.0,1.0
2867,51612.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2868,51613.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,1.0,1.0,1.0

In [13]:
CBQPFC.to_csv('CBQPFC_Ques_filter.csv')

# Processing Column of CBQPFC and CBQPFA

In [6]:
# CBQ505 - Eat at fast food/pizza places.
CBQPFA_reading1 = CBQPFA['CBQ505']
print('CBQPFA_reading1 shape = ', CBQPFA_reading1.shape)
print(CBQPFA_reading1.head())
print(CBQPFA_reading1.describe())

CBQPFA_reading1 shape =  (6022,)
SEQN
41475.0    2.0
41477.0    2.0
41479.0    1.0
41481.0    1.0
41482.0    2.0
Name: CBQ505, dtype: float64
count    4819.000000
mean        1.137995
std         0.369901
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         9.000000
Name: CBQ505, dtype: float64

In [7]:
# CBQ550 - Eat at restaurants w/ waiter (In the past 12 months, did you eat at a restaurant with waiter or waitress service?)
CBQPFA_reading2 = CBQPFA['CBQ550']
print('CBQPFA_reading2 shape = ', CBQPFA_reading2.shape)
print(CBQPFA_reading2.head())
print(CBQPFA_reading2.describe())

CBQPFA_reading2 shape =  (6022,)
SEQN
41475.0    1.0
41477.0    2.0
41479.0    1.0
41481.0    1.0
41482.0    2.0
Name: CBQ550, dtype: float64
count    4815.000000
mean        1.173001
std         0.407881
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         9.000000
Name: CBQ550, dtype: float64

In [8]:
# CBQ505 - Eat at fast food/pizza places( In the past 12 months, did you buy food from fast food or pizza places?)
CBQPFC_reading1 = CBQPFC['CBQ505']
print('CBQPFC_reading1 shape = ', CBQPFC_reading1.shape)
print(CBQPFC_reading1.head())
print(CBQPFC_reading1.describe())

CBQPFC_reading1 shape =  (2869,)
SEQN
41476.0    1.0
41478.0    NaN
41480.0    1.0
41488.0    NaN
41491.0    1.0
Name: CBQ505, dtype: float64
count    2249.000000
mean        1.081369
std         0.273463
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: CBQ505, dtype: float64

In [9]:
# CBQ550 - Eat at restaurants w/ waiter(In the past 12 months, did you eat at a restaurant with waiter or waitress service?)
CBQPFC_reading2 = CBQPFC['CBQ550']
print('CBQPFC_reading2 shape = ', CBQPFC_reading2.shape)
print(CBQPFC_reading2.head())
print(CBQPFC_reading2.describe())

CBQPFC_reading2 shape =  (2869,)
SEQN
41476.0    1.0
41478.0    NaN
41480.0    2.0
41488.0    NaN
41491.0    1.0
Name: CBQ550, dtype: float64
count    2248.000000
mean        1.212189
std         0.408949
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: CBQ550, dtype: float64

In [10]:
print('CBQPFA_reading1 missing values =  ', CBQPFA_reading1.isnull().sum(), 'from ', CBQPFA_reading1.shape[0], 'observations')
print('CBQPFA_reading2 missing values =  ', CBQPFA_reading2.isnull().sum(), 'from ', CBQPFA_reading2.shape[0], 'observations')
print('CBQPFC_reading1 missing values =  ', CBQPFC_reading1.isnull().sum(), 'from ', CBQPFC_reading1.shape[0], 'observations')
print('CBQPFC_reading2 missing values =  ', CBQPFC_reading2.isnull().sum(), 'from ', CBQPFC_reading2.shape[0], 'observations')

CBQPFA_reading1 missing values =   1203 from  6022 observations
CBQPFA_reading2 missing values =   1207 from  6022 observations
CBQPFC_reading1 missing values =   620 from  2869 observations
CBQPFC_reading2 missing values =   621 from  2869 observations

In [11]:
All_CBQPF = pd.concat([CBQPFA_reading1,CBQPFA_reading2,CBQPFC_reading1,CBQPFC_reading2],axis=1)
print('All_CBQPF shape = ', All_CBQPF.shape)
print(All_CBQPF.head())
All_CBQPF.describe()

All_CBQPF shape =  (8891, 4)
         CBQ505  CBQ550  CBQ505  CBQ550
SEQN
41475.0     2.0     1.0     NaN     NaN
41476.0     NaN     NaN     1.0     1.0
41477.0     2.0     2.0     NaN     NaN
41478.0     NaN     NaN     NaN     NaN
41479.0     1.0     1.0     NaN     NaN

            CBQ505       CBQ550       CBQ505       CBQ550
count  4819.000000  4815.000000  2249.000000  2248.000000
mean      1.137995     1.173001     1.081369     1.212189
std       0.369901     0.407881     0.273463     0.408949
min       1.000000     1.000000     1.000000     1.000000
25%       1.000000     1.000000     1.000000     1.000000
50%       1.000000     1.000000     1.000000     1.000000
75%       1.000000     1.000000     1.000000     1.000000
max       9.000000     9.000000     2.000000     2.000000

In [12]:
All_CBQPF.to_csv('all_CBQPF.csv')