#  Processing Laboratory - Cholesterol File (HDL, TRIGLY,TCHOL)

In [1]:
import numpy as np
import pandas as pd
import glob 
import os
import sys

In [2]:
os.getcwd()

'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Code'

In [ ]:
# Select working directory
# %cd C:\Users\Ganga\Desktop\Research\CDCDiab_2.0\Data\07-08\Examination
#%cd /Users/elgayaro/Main/Research/Healthcare/CDC-NHANES/Data/07-08/Examination

In [ ]:
#os.getcwd()

In [ ]:
# Omar
#allFiles = glob.glob(os.path.join('.',"*.XPT"))
#print(allFiles)

In [ ]:
# Omar
# Set desired file name
# fname = '.\\BMX_E.XPT'  # Ganga
#fname = './BMX_E.XPT'   # Omar
#BMX = pd.read_sas(fname, index='SEQN')
#BMX.shape

In [3]:
path = 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab'
allFiles = glob.glob(os.path.join(path,"*.XPT"))
print(allFiles)

['C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\ALB_CR_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\APOB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\BIOPRO_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\CARB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\CBC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\CHLMDA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\COTNAL_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\CRP_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\DEET_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\EPH_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\FASTQX_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\FERTIN_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\FOLATE_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\FOLFMS_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\GHB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\GLU_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HDL_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HEPA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HEPBD_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HEPB_S_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HEPC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HIV_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HPVSER_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HPVSWR_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HSV_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\IHG_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\OGTT_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\OPD_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PAH_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PBCD_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PERNT_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PFC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PHTHTE_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PHYTO_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PP_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\PSA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\SSEBV_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\SSHCV_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\SSUSG_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\TCHOL_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\TFR_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\THYROD_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\TRIGLY_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UAM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UAS_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UCPREG_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UHG_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UHM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UIO_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UPHOPM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\UPP_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VID_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VIT_B6_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VOCMWB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VOCWB_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\VOC_E.XPT']

In [4]:
HDL = pd.read_sas('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\HDL_E.XPT', index='SEQN')
HDL.shape

(8132, 2)

In [5]:
LDL = pd.read_sas('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\TRIGLY_E.XPT', index='SEQN')
LDL.shape

(3315, 5)

In [6]:
Total_chol = pd.read_sas('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Lab\\TCHOL_E.XPT', index='SEQN')
Total_chol.shape

(8132, 2)

In [7]:
A = set(HDL.columns)
B = set(LDL.columns)
C = set(Total_chol.columns)
print(sorted(A),sorted(B),sorted(C))

['LBDHDD', 'LBDHDDSI'] ['LBDLDL', 'LBDLDLSI', 'LBDTRSI', 'LBXTR', 'WTSAF2YR'] ['LBDTCSI', 'LBXTC']

In [8]:
HDL.dtypes,LDL.dtypes,Total_chol.dtypes

(LBDHDD      float64
 LBDHDDSI    float64
 dtype: object, WTSAF2YR    float64
 LBXTR       float64
 LBDTRSI     float64
 LBDLDL      float64
 LBDLDLSI    float64
 dtype: object, LBXTC      float64
 LBDTCSI    float64
 dtype: object)

In [9]:
HDL.describe().T

           count       mean        std   min    25%    50%    75%     max
LBDHDD    7387.0  52.036686  15.141436  7.00  41.00  50.00  61.00  155.00
LBDHDDSI  7387.0   1.345757   0.391473  0.18   1.06   1.29   1.58    4.01

In [10]:
LDL.describe().T

,count,mean,std,min,25%,50%,75%,max
WTSAF2YR,3315.0,74986.722745,72617.987905,5.397605e-79,26034.830,54827.201,94336.2335,404655.623
LBXTR,3099.0,131.477896,112.959009,1.200000e+01,73.000,107.000,158.0000,2549.000
LBDTRSI,3099.0,1.484389,1.275303,1.350000e-01,0.824,1.208,1.7840,28.778
LBDLDL,3035.0,110.910049,35.766973,2.300000e+01,85.000,108.000,132.0000,344.000
LBDLDLSI,3035.0,2.868153,0.924939,5.950000e-01,2.198,2.793,3.4140,8.896

In [11]:
Total_chol.describe().T

          count        mean        std    min     25%     50%     75%    max
LBXTC    7387.0  186.674699  42.151011  78.00  156.00  181.00  212.00  460.0
LBDTCSI  7387.0    4.827466   1.090053   2.02    4.03    4.68    5.48   11.9

In [13]:
Chol_reading_all = pd.concat([HDL,LDL,Total_chol ], axis=1)

In [14]:
#Please run the notebook till bottom
Chol_reading_all.describe().T

,count,mean,std,min,25%,50%,75%,max
LBDHDD,7387.0,52.036686,15.141436,7.000000e+00,41.000,50.000,61.0000,155.000
LBDHDDSI,7387.0,1.345757,0.391473,1.800000e-01,1.060,1.290,1.5800,4.010
WTSAF2YR,3315.0,74986.722745,72617.987905,5.397605e-79,26034.830,54827.201,94336.2335,404655.623
LBXTR,3099.0,131.477896,112.959009,1.200000e+01,73.000,107.000,158.0000,2549.000
LBDTRSI,3099.0,1.484389,1.275303,1.350000e-01,0.824,1.208,1.7840,28.778
LBDLDL,3035.0,110.910049,35.766973,2.300000e+01,85.000,108.000,132.0000,344.000
LBDLDLSI,3035.0,2.868153,0.924939,5.950000e-01,2.198,2.793,3.4140,8.896
LBXTC,7387.0,186.674699,42.151011,7.800000e+01,156.000,181.000,212.0000,460.000
LBDTCSI,7387.0,4.827466,1.090053,2.020000e+00,4.030,4.680,5.4800,11.900

In [32]:
Chol_reading_all.describe().T.to_csv('Chol_Select.csv')

In [15]:
Chol_reading_all.reset_index()

,SEQN,LBDHDD,LBDHDDSI,WTSAF2YR,LBXTR,LBDTRSI,LBDLDL,LBDLDLSI,LBXTC,LBDTCSI
0,41475.0,47.0,1.22,NaN,NaN,NaN,NaN,NaN,179.0,4.63
1,41476.0,45.0,1.16,NaN,NaN,NaN,NaN,NaN,143.0,3.70
2,41477.0,34.0,0.88,NaN,NaN,NaN,NaN,NaN,191.0,4.94
3,41479.0,47.0,1.22,1.998360e+04,99.0,1.118,121.0,3.129,188.0,4.86
4,41480.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,41481.0,NaN,NaN,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN
6,41482.0,43.0,1.11,NaN,NaN,NaN,NaN,NaN,158.0,4.09
7,41483.0,36.0,0.93,NaN,NaN,NaN,NaN,NaN,142.0,3.67
8,41485.0,35.0,0.91,4.344144e+04,172.0,1.942,119.0,3.077,188.0,4.86
9,41486.0,37.0,0.96,1.492377e+04,233.0,2.631,110.0,2.845,194.0,5.02
10,41487.0,37.0,0.96,2.124669e+05,124.0,1.400,105.0,2.715,167.0,4.32
11,41489.0,62.0,1.60,6.283678e+04,101.0,1.140,106.0,2.741,188.0,4.86
12,41490.0,90.0,2.33,NaN,NaN,NaN,NaN,NaN,225.0,5.82
13,41491.0,53.0,1.37,NaN,NaN,NaN,NaN,NaN,152.0,3.93
14,41492.0,76.0,1.97,2.452812e+04,61.0,0.689,114.0,2.948,202.0,5.22
15,41493.0,73.0,1.89,NaN,NaN,NaN,NaN,NaN,234.0,6.05
16,41494.0,47.0,1.22,3.041933e+04,113.0,1.276,153.0,3.957,223.0,5.77
17,41495.0,47.0,1.22,2.001344e+05,152.0,1.716,91.0,2.353,168.0,4.34
18,41496.0,35.0,0.91,NaN,NaN,NaN,NaN,NaN,218.0,5.64
19,41498.0,47.0,1.22,2.804372e+04,71.0,0.802,88.0,2.276,149.0,3.85
20,41499.0,73.0,1.89,NaN,NaN,NaN,NaN,NaN,199.0,5.15
21,41500.0,37.0,0.96,NaN,NaN,NaN,NaN,NaN,137.0,3.54
22,41501.0,48.0,1.24,6.208276e+04,167.0,1.885,77.0,1.991,158.0,4.09
23,41502.0,39.0,1.01,6.605435e+04,89.0,1.005,108.0,2.793,165.0,4.27
24,41503.0,39.0,1.01,NaN,NaN,NaN,NaN,NaN,128.0,3.31
25,41504.0,67.0,1.73,NaN,NaN,NaN,NaN,NaN,172.0,4.45
26,41506.0,55.0,1.42,7.649553e+04,131.0,1.479,119.0,3.077,200.0,5.17
27,41507.0,47.0,1.22,NaN,NaN,NaN,NaN,NaN,187.0,4.84
28,41509.0,48.0,1.24,NaN,NaN,NaN,NaN,NaN,223.0,5.77
29,41510.0,65.0,1.68,NaN,NaN,NaN,NaN,NaN,184.0,4.76
...,...,...,...,...,...,...,...,...,...,...
8102,51587.0,49.0,1.27,6.961518e+04,70.0,0.790,140.0,3.620,203.0,5.25
8103,51588.0,40.0,1.03,3.065438e+04,47.0,0.531,106.0,2.741,155.0,4.01
8104,51589.0,84.0,2.17,6.141853e+04,88.0,0.994,70.0,1.810,172.0,4.45
8105,51590.0,56.0,1.45,NaN,NaN,NaN,NaN,NaN,191.0,4.94
8106,51591.0,NaN,NaN,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN
8107,51592.0,NaN,NaN,5.687512e+04,NaN,NaN,NaN,NaN,NaN,NaN
8108,51593.0,51.0,1.32,NaN,NaN,NaN,NaN,NaN,166.0,4.29
8109,51594.0,51.0,1.32,NaN,NaN,NaN,NaN,NaN,227.0,5.87
8110,51596.0,51.0,1.32,NaN,NaN,NaN,NaN,NaN,205.0,5.30
8111,51597.0,63.0,1.63,NaN,NaN,NaN,NaN,NaN,158.0,4.09
8112,51601.0,42.0,1.09,NaN,NaN,NaN,NaN,NaN,149.0,3.85
8113,51603.0,83.0,2.15,5.397605e-79,73.0,0.824,81.0,2.095,179.0,4.63
8114,51604.0,56.0,1.45,NaN,NaN,NaN,NaN,NaN,179.0,4.63
8115,51606.0,74.0,1.91,NaN,NaN,NaN,NaN,NaN,224.0,5.79
8116,51608.0,35.0,0.91,NaN,NaN,NaN,NaN,NaN,171.0,4.42
8117,51609.0,64.0,1.66,NaN,NaN,NaN,NaN,NaN,274.0,7.09
8118,51610.0,46.0,1.19,NaN,NaN,NaN,NaN,NaN,185.0,4.78
8119,51611.0,50.0,1.29,5.397605e-79,178.0,2.010,167.0,4.319,253.0,6.54
8120,51612.0,45.0,1.16,NaN,NaN,NaN,NaN,NaN,156.0,4.03
8121,51613.0,43.0,1.11,9.531321e+04,115.0,1.298,87.0,2.250,153.0,3.96
8122,51614.0,42.0,1.09,NaN,NaN,NaN,NaN,NaN,290.0,7.50
8123,51615.0,NaN,NaN,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN
8124,51616.0,72.0,1.86,1.442452e+05,127.0,1.434,76.0,1.965,173.0,4.47
8125,51617.0,68.0,1.76,1.379351e+04,76.0,0.858,88.0,2.276,171.0,4.42
8126,51618.0,47.0,1.22,2.220151e+05,103.0,1.163,124.0,3.207,192.0,4.97
8127,51619.0,50.0,1.29,NaN,NaN,NaN,NaN,NaN,220.0,5.69
8128,51620.0,41.0,1.06,5.470461e+04,223.0,2.518,158.0,4.086,244.0,6.31
8129,51621.0,45.0,1.16,NaN,NaN,NaN,NaN,NaN,128.0,3.31
8130,51622.0,65.0,1.68,NaN,NaN,NaN,NaN,NaN,208.0,5.38
8131,51623.0,42.0,1.09,6.689679e+04,56.0,0.632,61.0,1.577,114.0,2.95

In [16]:
Chol_reading_all.to_csv('Total_Chol_Lab_filter.csv')

# Processing Column of all 3 Cholesterol Files

## We read three different file containing different form of Cholesterol. 
## HDL, LDL and total cholesterol

In [24]:
HDL_reading1 = HDL
print('HDL_reading1 shape = ', HDL_reading1.shape)
print(HDL_reading1.head())
print(HDL_reading1.describe())

HDL_reading1 shape =  (8132, 2)
         LBDHDD  LBDHDDSI
SEQN
41475.0    47.0      1.22
41476.0    45.0      1.16
41477.0    34.0      0.88
41479.0    47.0      1.22
41480.0     NaN       NaN
            LBDHDD     LBDHDDSI
count  7387.000000  7387.000000
mean     52.036686     1.345757
std      15.141436     0.391473
min       7.000000     0.180000
25%      41.000000     1.060000
50%      50.000000     1.290000
75%      61.000000     1.580000
max     155.000000     4.010000

In [25]:
LDL_reading1 = LDL
print('LDL_reading1 shape = ', LDL_reading1.shape)
print(LDL_reading1.head())
print(LDL_reading1.describe())

LDL_reading1 shape =  (3315, 5)
             WTSAF2YR  LBXTR  LBDTRSI  LBDLDL  LBDLDLSI
SEQN
41479.0  1.998360e+04   99.0    1.118   121.0     3.129
41481.0  5.397605e-79    NaN      NaN     NaN       NaN
41485.0  4.344144e+04  172.0    1.942   119.0     3.077
41486.0  1.492377e+04  233.0    2.631   110.0     2.845
41487.0  2.124669e+05  124.0    1.400   105.0     2.715
           WTSAF2YR        LBXTR      LBDTRSI       LBDLDL     LBDLDLSI
count  3.315000e+03  3099.000000  3099.000000  3035.000000  3035.000000
mean   7.498672e+04   131.477896     1.484389   110.910049     2.868153
std    7.261799e+04   112.959009     1.275303    35.766973     0.924939
min    5.397605e-79    12.000000     0.135000    23.000000     0.595000
25%    2.603483e+04    73.000000     0.824000    85.000000     2.198000
50%    5.482720e+04   107.000000     1.208000   108.000000     2.793000
75%    9.433623e+04   158.000000     1.784000   132.000000     3.414000
max    4.046556e+05  2549.000000    28.778000   344.000000     8.896000

In [26]:
Total_chol_reading3 = Total_chol
print('Total_chol shape = ', Total_chol_reading3.shape)
print(Total_chol_reading3.head())
print(Total_chol_reading3.describe())

Total_chol shape =  (8132, 2)
         LBXTC  LBDTCSI
SEQN
41475.0  179.0     4.63
41476.0  143.0     3.70
41477.0  191.0     4.94
41479.0  188.0     4.86
41480.0    NaN      NaN
             LBXTC      LBDTCSI
count  7387.000000  7387.000000
mean    186.674699     4.827466
std      42.151011     1.090053
min      78.000000     2.020000
25%     156.000000     4.030000
50%     181.000000     4.680000
75%     212.000000     5.480000
max     460.000000    11.900000

In [27]:
print('HDL_reading1 missing values =  ', HDL_reading1.isnull().sum(), 'from ', HDL_reading1.shape, 'observations')
print('LDL_reading1 missing values = ', LDL_reading1.isnull().sum(), 'from ', LDL_reading1.shape, 'observations')
print('Total_chol_reading3 missing values =  ', Total_chol_reading3.isnull().sum(), 'from ', Total_chol_reading3.shape, 'observations')

HDL_reading1 missing values =   LBDHDD      745
LBDHDDSI    745
dtype: int64 from  (8132, 2) observations
LDL_reading1 missing values =  WTSAF2YR      0
LBXTR       216
LBDTRSI     216
LBDLDL      280
LBDLDLSI    280
dtype: int64 from  (3315, 5) observations
Total_chol_reading3 missing values =   LBXTC      745
LBDTCSI    745
dtype: int64 from  (8132, 2) observations

In [28]:
Chol_reading_all = pd.concat([HDL_reading1, LDL_reading1,Total_chol_reading3,], axis=1)
print('Chol_reading_all shape = ', Chol_reading_all.shape)
print(Chol_reading_all.head())

Chol_reading_all shape =  (8132, 9)
         LBDHDD  LBDHDDSI  WTSAF2YR  LBXTR  LBDTRSI  LBDLDL  LBDLDLSI  LBXTC  \
SEQN
41475.0    47.0      1.22       NaN    NaN      NaN     NaN       NaN  179.0
41476.0    45.0      1.16       NaN    NaN      NaN     NaN       NaN  143.0
41477.0    34.0      0.88       NaN    NaN      NaN     NaN       NaN  191.0
41479.0    47.0      1.22   19983.6   99.0    1.118   121.0     3.129  188.0
41480.0     NaN       NaN       NaN    NaN      NaN     NaN       NaN    NaN

         LBDTCSI
SEQN
41475.0     4.63
41476.0     3.70
41477.0     4.94
41479.0     4.86
41480.0      NaN

In [29]:
Chol_reading_all_mean = Chol_reading_all.mean(axis=1, skipna=1)
print('Type of Chol_reading_all_mean = ', Chol_reading_all_mean.dtype)
print(Chol_reading_all_mean.name)
Chol_reading_all_mean.name = 'Total_Chol_mean'
print(Chol_reading_all_mean.name)
Chol_reading_all_mean.isnull().sum()

Type of Chol_reading_all_mean =  float64
None
Total_Chol_mean

532

In [30]:
Chol_mean_all = pd.concat([Chol_reading_all, Chol_reading_all_mean], axis=1)
print('Chol_mean_all shape = ', Chol_mean_all.shape)
print(Chol_mean_all.head())

Chol_mean_all shape =  (8132, 10)
         LBDHDD  LBDHDDSI  WTSAF2YR  LBXTR  LBDTRSI  LBDLDL  LBDLDLSI  LBXTC  \
SEQN
41475.0    47.0      1.22       NaN    NaN      NaN     NaN       NaN  179.0
41476.0    45.0      1.16       NaN    NaN      NaN     NaN       NaN  143.0
41477.0    34.0      0.88       NaN    NaN      NaN     NaN       NaN  191.0
41479.0    47.0      1.22   19983.6   99.0    1.118   121.0     3.129  188.0
41480.0     NaN       NaN       NaN    NaN      NaN     NaN       NaN    NaN

         LBDTCSI  Total_Chol_mean
SEQN
41475.0     4.63          57.9625
41476.0     3.70          48.2150
41477.0     4.94          57.7050
41479.0     4.86        2272.1030
41480.0      NaN              NaN