#  Processing Questionnaire - Income (INQ) file

In [1]:
import numpy as np
import pandas as pd
import glob 
import os
import sys

In [2]:
os.getcwd()

'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Code'

In [ ]:
# Select working directory
# %cd C:\Users\Ganga\Desktop\Research\CDCDiab_2.0\Data\07-08\Examination
#%cd /Users/elgayaro/Main/Research/Healthcare/CDC-NHANES/Data/07-08/Examination

In [ ]:
#os.getcwd()

In [ ]:
#allFiles = glob.glob(os.path.join('.',"*.XPT"))
#print(allFiles)

In [ ]:
# Set desired file name
# fname = '.\\BMX_E.XPT'  # Ganga
#fname = './BMX_E.XPT'   # Omar
#BMX = pd.read_sas(fname, index='SEQN')
#BMX.shape

In [3]:
path = 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest'
allFiles = glob.glob(os.path.join(path,"*.XPT"))
print(allFiles)

['C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ACQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ALQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\AQQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\AUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\BHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\BPQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQPFA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQPFC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CDQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DBQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DPQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ECQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\FSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HOQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\IMQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\INQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\KIQ_P_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\KIQ_U_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\MCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PAQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PFQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PUQMEC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RDQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RXQ_RX_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SLQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQFAM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQRTU_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SXQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\VIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\WHQMEC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\WHQ_E.XPT']

In [4]:
INQ = pd.read_sas('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\INQ_E.XPT', index='SEQN')
INQ.shape

(10149, 14)

In [5]:
INQ.head()

,INQ020,INQ012,INQ030,INQ060,INQ080,INQ090,INQ132,INQ140,INQ150,IND235,INDFMMPI,INDFMMPC,INQ244,IND247
SEQN,,,,,,,,,,,,,,
41475.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,5.0,1.75,2.0,2.0,1.0
41476.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,12.0,5.00,3.0,NaN,NaN
41477.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,4.0,1.29,1.0,2.0,1.0
41478.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,3.0,0.45,1.0,2.0,1.0
41479.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,7.0,1.69,2.0,NaN,NaN

In [6]:
INQ.isnull().sum()

INQ020        94
INQ012        94
INQ030        94
INQ060        94
INQ080        94
INQ090        94
INQ132        94
INQ140        94
INQ150        94
IND235       411
INDFMMPI    1192
INDFMMPC     411
INQ244      4783
IND247      5717
dtype: int64

In [7]:
INQ.notnull().count()

INQ020      10149
INQ012      10149
INQ030      10149
INQ060      10149
INQ080      10149
INQ090      10149
INQ132      10149
INQ140      10149
INQ150      10149
IND235      10149
INDFMMPI    10149
INDFMMPC    10149
INQ244      10149
IND247      10149
dtype: int64

In [8]:
INQ.describe().T

            count       mean        std           min   25%   50%   75%   max
INQ020    10055.0   1.232024   0.638566  1.000000e+00  1.00  1.00   1.0   9.0
INQ012    10055.0   1.848434   0.439837  1.000000e+00  2.00  2.00   2.0   9.0
INQ030    10055.0   1.781104   0.543073  1.000000e+00  2.00  2.00   2.0   9.0
INQ060    10055.0   1.950373   0.343492  1.000000e+00  2.00  2.00   2.0   9.0
INQ080    10055.0   1.893187   0.474251  1.000000e+00  2.00  2.00   2.0   9.0
INQ090    10055.0   1.942815   0.438150  1.000000e+00  2.00  2.00   2.0   9.0
INQ132    10055.0   1.970960   0.367455  1.000000e+00  2.00  2.00   2.0   9.0
INQ140    10055.0   1.785679   0.686708  1.000000e+00  1.00  2.00   2.0   9.0
INQ150    10055.0   1.872302   0.443555  1.000000e+00  2.00  2.00   2.0   9.0
IND235     9738.0  13.201068  23.603505  1.000000e+00  4.00  7.00  10.0  99.0
INDFMMPI   8957.0   2.079126   1.521069  5.397605e-79  0.87  1.64   3.0   5.0
INDFMMPC   9738.0   2.137503   1.220351  1.000000e+00  1.00  2.00   3.0   9.0
INQ244     5366.0   2.107715   1.266070  1.000000e+00  2.00  2.00   2.0   9.0
IND247     4432.0   5.515569  19.216855  1.000000e+00  1.00  1.00   1.0  99.0

In [9]:
INQ_filter = INQ.filter(['INQ020','INQ012','INQ030','INQ060','INQ080','INQ090','INQ132','INQ140','INQ150','INDFMMPI'])

In [10]:
INQ_filter.describe().T

            count      mean       std           min   25%   50%  75%  max
INQ020    10055.0  1.232024  0.638566  1.000000e+00  1.00  1.00  1.0  9.0
INQ012    10055.0  1.848434  0.439837  1.000000e+00  2.00  2.00  2.0  9.0
INQ030    10055.0  1.781104  0.543073  1.000000e+00  2.00  2.00  2.0  9.0
INQ060    10055.0  1.950373  0.343492  1.000000e+00  2.00  2.00  2.0  9.0
INQ080    10055.0  1.893187  0.474251  1.000000e+00  2.00  2.00  2.0  9.0
INQ090    10055.0  1.942815  0.438150  1.000000e+00  2.00  2.00  2.0  9.0
INQ132    10055.0  1.970960  0.367455  1.000000e+00  2.00  2.00  2.0  9.0
INQ140    10055.0  1.785679  0.686708  1.000000e+00  1.00  2.00  2.0  9.0
INQ150    10055.0  1.872302  0.443555  1.000000e+00  2.00  2.00  2.0  9.0
INDFMMPI   8957.0  2.079126  1.521069  5.397605e-79  0.87  1.64  3.0  5.0

In [14]:
INQ_filter.describe().T.to_csv('INQ_Select.csv')

In [11]:
INQ_filter.reset_index()

,SEQN,INQ020,INQ012,INQ030,INQ060,INQ080,INQ090,INQ132,INQ140,INQ150,INDFMMPI
0,41475.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.75
1,41476.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,5.00
2,41477.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.29
3,41478.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,0.45
4,41479.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.69
5,41480.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.68
6,41481.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.64
7,41482.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,1.90
8,41483.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,1.23
9,41484.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,0.36
10,41485.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.03
11,41486.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.54
12,41487.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,5.00
13,41488.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.40
14,41489.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.45
15,41490.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,1.75
16,41491.0,7.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN
17,41492.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.05
18,41493.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.71
19,41494.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.09
20,41495.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,5.00
21,41496.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.49
22,41497.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.89
23,41498.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,5.00
24,41499.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.74
25,41500.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.23
26,41501.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,4.11
27,41502.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.07
28,41503.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,41504.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,2.63
...,...,...,...,...,...,...,...,...,...,...,...
10119,51594.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.94
10120,51595.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.66
10121,51596.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,5.00
10122,51597.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.85
10123,51598.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.0,1.12
10124,51599.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,0.73
10125,51600.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,0.74
10126,51601.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,4.65
10127,51602.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN
10128,51603.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,5.00
10129,51604.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,3.40
10130,51605.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.36
10131,51606.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,1.31
10132,51607.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.90
10133,51608.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,0.72
10134,51609.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.05
10135,51610.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN
10136,51611.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,4.19
10137,51612.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,0.34
10138,51613.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.74
10139,51614.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.53
10140,51615.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN
10141,51616.0,1.0,2.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,3.86
10142,51617.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.73
10143,51618.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.82
10144,51619.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.99
10145,51620.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.63
10146,51621.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN
10147,51622.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,1.0,2.0,1.74
10148,51623.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN

In [12]:
INQ_filter.to_csv('INQ_Ques_filter.csv')

# Processing Column of INQ

In [5]:
# IND235 - Monthly family income(Monthly family income (reported as a range value in dollars).)
INQ_reading1 = INQ['IND235']
print('INQ_reading1 shape = ', INQ_reading1.shape)
print(INQ_reading1.head())
print(INQ_reading1.describe())

INQ_reading1 shape =  (10149,)
SEQN
41475.0     5.0
41476.0    12.0
41477.0     4.0
41478.0     3.0
41479.0     7.0
Name: IND235, dtype: float64
count    9738.000000
mean       13.201068
std        23.603505
min         1.000000
25%         4.000000
50%         7.000000
75%        10.000000
max        99.000000
Name: IND235, dtype: float64

In [8]:
print('INQ_reading1 missing values =  ', INQ_reading1.isnull().sum(), 'from ', INQ_reading1.shape[0], 'observations')

GHB missing values =   490 from  6917 observations

In [ ]:
All_INQ.to_csv('all_INQ.csv')