#  Processing Questionnaire - Drug Use (DUQ) file

In [1]:
import numpy as np
import pandas as pd
import glob 
import os
import sys

In [2]:
os.getcwd()

'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Code'

In [ ]:
# Select working directory
# %cd C:\Users\Ganga\Desktop\Research\CDCDiab_2.0\Data\07-08\Examination
#%cd /Users/elgayaro/Main/Research/Healthcare/CDC-NHANES/Data/07-08/Examination

In [ ]:
#os.getcwd()

In [ ]:
#allFiles = glob.glob(os.path.join('.',"*.XPT"))
#print(allFiles)

In [ ]:
# Set desired file name
# fname = '.\\BMX_E.XPT'  # Ganga
#fname = './BMX_E.XPT'   # Omar
#BMX = pd.read_sas(fname, index='SEQN')
#BMX.shape

In [3]:
path = 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest'
allFiles = glob.glob(os.path.join(path,"*.XPT"))
print(allFiles)

['C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ACQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ALQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\AQQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\AUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\BHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\BPQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQPFA_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQPFC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CBQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\CDQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DBQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DPQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\ECQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\FSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HOQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\HUQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\IMQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\INQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\KIQ_P_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\KIQ_U_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\MCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OCQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\OSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PAQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PFQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\PUQMEC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RDQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RHQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\RXQ_RX_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SLQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQFAM_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQRTU_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SMQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SSQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\SXQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\VIQ_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\WHQMEC_E.XPT', 'C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\WHQ_E.XPT']

In [4]:
DUQ = pd.read_sas('C:\\Users\\Ganga\\Desktop\\Research\\CDCDiab_2.0\\Data\\07-08\\Quest\\DUQ_E.XPT', index='SEQN')
DUQ.shape

(4625, 36)

In [5]:
DUQ.head()

,DUAISC,DUQ200,DUQ210,DUQ220Q,DUQ220U,DUQ230,DUQ240,DUQ250,DUQ260,DUQ270Q,...,DUQ380B,DUQ380C,DUQ380D,DUQ380E,DUQ390,DUQ400Q,DUQ400U,DUQ410,DUQ420,DUQ430
SEQN,,,,,,,,,,,,,,,,,,,,,
41475.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41479.0,1.0,2.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41481.0,1.0,1.0,20.0,4.0,3.0,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
41482.0,1.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41483.0,1.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
DUQ.isnull().sum()

DUAISC        0
DUQ200     1357
DUQ210     2814
DUQ220Q    2814
DUQ220U    2814
DUQ230     4233
DUQ240      497
DUQ250     3930
DUQ260     4005
DUQ270Q    4005
DUQ270U    4005
DUQ272     4005
DUQ280     4553
DUQ290     3930
DUQ300     4550
DUQ310Q    4550
DUQ310U    4550
DUQ320     4619
DUQ330     3930
DUQ340     4385
DUQ350Q    4385
DUQ350U    4385
DUQ352     4385
DUQ360     4610
DUQ370      497
DUQ380A    4565
DUQ380B    4580
DUQ380C    4591
DUQ380D    4615
DUQ380E    4599
DUQ390     4512
DUQ400Q    4512
DUQ400U    4512
DUQ410     4512
DUQ420     4532
DUQ430     2764
dtype: int64

In [7]:
DUQ.describe().T

,count,mean,std,min,25%,50%,75%,max
DUAISC,4625.0,1.214703,0.619011,1.000000e+00,1.0,1.0,1.00,3.0
DUQ200,3268.0,1.468176,0.632671,1.000000e+00,1.0,1.0,2.00,9.0
DUQ210,1811.0,17.380453,5.159065,1.000000e+00,15.0,17.0,19.00,99.0
DUQ220Q,1811.0,362.993374,1752.209108,5.397605e-79,3.0,8.0,20.00,9999.0
DUQ220U,1811.0,3.459967,1.477987,1.000000e+00,3.0,4.0,4.00,9.0
DUQ230,392.0,12.099490,12.776369,1.000000e+00,2.0,5.0,22.00,99.0
DUQ240,4128.0,1.871609,0.634588,1.000000e+00,2.0,2.0,2.00,9.0
DUQ250,695.0,1.067626,0.432508,1.000000e+00,1.0,1.0,1.00,9.0
DUQ260,620.0,22.061290,6.695991,5.397605e-79,18.0,20.0,25.00,99.0
DUQ270Q,620.0,234.769355,1375.373391,5.397605e-79,3.0,9.5,20.00,9999.0
DUQ270U,620.0,3.667742,1.136525,1.000000e+00,4.0,4.0,4.00,9.0
DUQ272,620.0,4.401613,8.291440,1.000000e+00,2.0,3.0,5.00,99.0
DUQ280,72.0,6.000000,12.812846,1.000000e+00,1.0,2.5,5.00,99.0
DUQ290,695.0,1.886331,0.426128,1.000000e+00,2.0,2.0,2.00,9.0
DUQ300,75.0,23.266667,6.730996,9.000000e+00,18.0,21.0,28.00,46.0
DUQ310Q,75.0,222.893333,1258.853249,5.397605e-79,6.0,15.0,25.00,7777.0
DUQ310U,75.0,3.773333,1.007718,1.000000e+00,4.0,4.0,4.00,7.0
DUQ320,6.0,17.000000,12.884099,1.000000e+00,6.0,19.0,28.25,30.0
DUQ330,695.0,1.634532,0.481908,1.000000e+00,1.0,2.0,2.00,2.0
DUQ340,240.0,22.270833,6.800011,7.000000e+00,17.0,21.0,25.00,50.0
DUQ350Q,240.0,86.987500,815.026423,1.000000e+00,4.0,9.5,20.00,9999.0
DUQ350U,240.0,3.783333,0.825162,1.000000e+00,4.0,4.0,4.00,9.0
DUQ352,240.0,3.829167,5.012117,1.000000e+00,2.0,3.0,5.00,77.0
DUQ360,15.0,6.666667,7.961216,1.000000e+00,1.0,2.0,12.50,20.0
DUQ370,4128.0,1.990795,0.389979,1.000000e+00,2.0,2.0,2.00,9.0
DUQ380A,60.0,1.133333,1.032796,1.000000e+00,1.0,1.0,1.00,9.0
DUQ380B,45.0,2.000000,0.000000,2.000000e+00,2.0,2.0,2.00,2.0
DUQ380C,34.0,3.000000,0.000000,3.000000e+00,3.0,3.0,3.00,3.0
DUQ380D,10.0,4.000000,0.000000,4.000000e+00,4.0,4.0,4.00,4.0
DUQ380E,26.0,5.000000,0.000000,5.000000e+00,5.0,5.0,5.00,5.0
DUQ390,113.0,25.725664,11.478433,9.000000e+00,19.0,23.0,28.00,77.0
DUQ400Q,113.0,331.876106,1659.888858,1.000000e+00,6.0,14.0,25.00,9999.0
DUQ400U,113.0,3.787611,1.235280,1.000000e+00,4.0,4.0,4.00,9.0
DUQ410,113.0,4.106195,9.178160,1.000000e+00,2.0,3.0,5.00,99.0
DUQ420,93.0,2.795699,1.543282,1.000000e+00,1.0,3.0,4.00,9.0
DUQ430,1861.0,1.904352,0.364393,1.000000e+00,2.0,2.0,2.00,9.0

In [8]:
DUQ_filter = DUQ.filter(['DUQ200','DUQ240','DUQ250','DUQ370'])

In [9]:
DUQ_filter.describe().T

         count      mean       std  min  25%  50%  75%  max
DUQ200  3268.0  1.468176  0.632671  1.0  1.0  1.0  2.0  9.0
DUQ240  4128.0  1.871609  0.634588  1.0  2.0  2.0  2.0  9.0
DUQ250   695.0  1.067626  0.432508  1.0  1.0  1.0  1.0  9.0
DUQ370  4128.0  1.990795  0.389979  1.0  2.0  2.0  2.0  9.0

In [10]:
DUQ_filter.describe().T.to_csv('DUQ_Select.csv')

In [10]:
DUQ_filter.reset_index()

         SEQN  DUQ200  DUQ240  DUQ250  DUQ370
0     41475.0     NaN     2.0     NaN     2.0
1     41479.0     2.0     2.0     NaN     2.0
2     41481.0     1.0     2.0     NaN     2.0
3     41482.0     NaN     9.0     NaN     2.0
4     41483.0     NaN     2.0     NaN     2.0
5     41485.0     2.0     2.0     NaN     2.0
6     41486.0     NaN     2.0     NaN     2.0
7     41487.0     2.0     2.0     NaN     2.0
8     41489.0     2.0     2.0     NaN     2.0
9     41490.0     NaN     2.0     NaN     2.0
10    41494.0     1.0     1.0     1.0     2.0
11    41495.0     NaN     2.0     NaN     2.0
12    41496.0     NaN     2.0     NaN     2.0
13    41498.0     NaN     2.0     NaN     2.0
14    41502.0     1.0     2.0     NaN     2.0
15    41504.0     NaN     2.0     NaN     2.0
16    41509.0     1.0     1.0     1.0     2.0
17    41510.0     1.0     2.0     NaN     2.0
18    41511.0     2.0     1.0     1.0     2.0
19    41518.0     1.0     2.0     NaN     2.0
20    41523.0     1.0     2.0     NaN     2.0
21    41525.0     1.0     1.0     1.0     1.0
22    41526.0     NaN     2.0     NaN     2.0
23    41527.0     2.0     2.0     NaN     2.0
24    41528.0     NaN     2.0     NaN     2.0
25    41531.0     2.0     2.0     NaN     2.0
26    41534.0     NaN     NaN     NaN     NaN
27    41536.0     2.0     2.0     NaN     2.0
28    41539.0     1.0     2.0     NaN     2.0
29    41541.0     2.0     2.0     NaN     2.0
...       ...     ...     ...     ...     ...
4595  51562.0     NaN     NaN     NaN     NaN
4596  51564.0     2.0     2.0     NaN     2.0
4597  51569.0     1.0     1.0     1.0     2.0
4598  51570.0     NaN     2.0     NaN     2.0
4599  51575.0     NaN     2.0     NaN     2.0
4600  51576.0     2.0     2.0     NaN     2.0
4601  51578.0     NaN     NaN     NaN     NaN
4602  51579.0     2.0     2.0     NaN     2.0
4603  51580.0     2.0     2.0     NaN     2.0
4604  51583.0     NaN     2.0     NaN     2.0
4605  51584.0     1.0     2.0     NaN     2.0
4606  51587.0     2.0     2.0     NaN     2.0
4607  51589.0     1.0     2.0     NaN     2.0
4608  51590.0     2.0     2.0     NaN     2.0
4609  51592.0     NaN     2.0     NaN     2.0
4610  51593.0     NaN     2.0     NaN     2.0
4611  51594.0     1.0     1.0     1.0     2.0
4612  51596.0     2.0     2.0     NaN     2.0
4613  51603.0     NaN     NaN     NaN     NaN
4614  51604.0     2.0     2.0     NaN     2.0
4615  51608.0     2.0     2.0     NaN     2.0
4616  51610.0     NaN     NaN     NaN     NaN
4617  51611.0     2.0     2.0     NaN     2.0
4618  51614.0     1.0     1.0     1.0     1.0
4619  51615.0     NaN     NaN     NaN     NaN
4620  51616.0     NaN     2.0     NaN     2.0
4621  51618.0     2.0     2.0     NaN     2.0
4622  51619.0     NaN     2.0     NaN     2.0
4623  51620.0     1.0     2.0     NaN     2.0
4624  51622.0     NaN     2.0     NaN     2.0

[4625 rows x 5 columns]

In [11]:
DUQ_filter.to_csv('DUQ_Ques_filter.csv')

# Processing Column of DUQ

In [5]:
# DUQ200 - Ever used marijuana or hashish
DUQ_reading1 = DUQ['DUQ200']
print('DUQ_reading1 shape = ', DUQ_reading1.shape)
print(DUQ_reading1.head())
print(DUQ_reading1.describe())

DUQ_reading1 shape =  (4625,)
SEQN
41475.0    NaN
41479.0    2.0
41481.0    1.0
41482.0    NaN
41483.0    NaN
Name: DUQ200, dtype: float64
count    3268.000000
mean        1.468176
std         0.632671
min         1.000000
25%         1.000000
50%         1.000000
75%         2.000000
max         9.000000
Name: DUQ200, dtype: float64

In [6]:
# DUQ240 - Ever used cocaine/heroin/methamphetamine
DUQ_reading2 = DUQ['DUQ240']
print('DUQ_reading2 shape = ', DUQ_reading2.shape)
print(DUQ_reading2.head())
print(DUQ_reading2.describe())

DUQ_reading2 shape =  (4625,)
SEQN
41475.0    2.0
41479.0    2.0
41481.0    2.0
41482.0    9.0
41483.0    2.0
Name: DUQ240, dtype: float64
count    4128.000000
mean        1.871609
std         0.634588
min         1.000000
25%         2.000000
50%         2.000000
75%         2.000000
max         9.000000
Name: DUQ240, dtype: float64

In [7]:
# DUQ250 - Ever use any form of cocaine
DUQ_reading3 = DUQ['DUQ250']
print('DUQ_reading3 shape = ', DUQ_reading3.shape)
print(DUQ_reading3.head())
print(DUQ_reading3.describe())

DUQ_reading3 shape =  (4625,)
SEQN
41475.0   NaN
41479.0   NaN
41481.0   NaN
41482.0   NaN
41483.0   NaN
Name: DUQ250, dtype: float64
count    695.000000
mean       1.067626
std        0.432508
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        9.000000
Name: DUQ250, dtype: float64

In [8]:
print('DUQ_reading1 missing values =  ', DUQ_reading1.isnull().sum(), 'from ', DUQ_reading1.shape[0], 'observations')
print('DUQ_reading2 missing values =  ', DUQ_reading2.isnull().sum(), 'from ', DUQ_reading2.shape[0], 'observations')
print('DUQ_reading3 missing values =  ', DUQ_reading3.isnull().sum(), 'from ', DUQ_reading3.shape[0], 'observations')

DUQ_reading1 missing values =   1357 from  4625 observations
DUQ_reading2 missing values =   497 from  4625 observations
DUQ_reading3 missing values =   3930 from  4625 observations

In [9]:
All_DUQ = pd.concat([DUQ_reading1,DUQ_reading2,DUQ_reading3],axis=1)
print('All_DUQ shape = ', All_DUQ.shape)
print(All_DUQ.head())
All_DUQ.describe()

All_DUQ shape =  (4625, 3)
         DUQ200  DUQ240  DUQ250
SEQN
41475.0     NaN     2.0     NaN
41479.0     2.0     2.0     NaN
41481.0     1.0     2.0     NaN
41482.0     NaN     9.0     NaN
41483.0     NaN     2.0     NaN

            DUQ200       DUQ240      DUQ250
count  3268.000000  4128.000000  695.000000
mean      1.468176     1.871609    1.067626
std       0.632671     0.634588    0.432508
min       1.000000     1.000000    1.000000
25%       1.000000     2.000000    1.000000
50%       1.000000     2.000000    1.000000
75%       2.000000     2.000000    1.000000
max       9.000000     9.000000    9.000000

In [ ]:
All_DUQ.to_csv('all_DUQ.csv')